# Generated by Django 5.1.6 on 2025-03-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_recipe', models.CharField(max_length=100)),
                ('description_recipe', models.TextField()),
                ('image_recipe', models.ImageField(upload_to='recipes')),
            ],
        ),
    ]
